services:
  # 🍦 1. Deploy the Node/Express Backend Server
  - type: web
    name: cafepanna-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb://offline_fallback_bypass" # Satisfies the process env safety check

  # 🍨 2. Deploy the Vite React Frontend Website
  - type: web
    name: cafepanna-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        src: /*
        dest: /index.html
  